# cloudbuild.yaml
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/image-gallery:$SHORT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/image-gallery:$SHORT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "image-gallery-website" # Replace with your service name if different
      - "--image"
      - "gcr.io/$PROJECT_ID/image-gallery:$SHORT_SHA"
      - "--platform"
      - "managed"
      - "--region"
      - "asia-southeast1" # Replace with your desired region
      - "--allow-unauthenticated"
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

serviceAccount: "upload-to-bucket@rugged-precept-451103-n9.iam.gserviceaccount.com" # Replace with your service account email

substitutions:
    _BUCKET_NAME: "image-web-app" # Replace with your bucket name